docker:
	docker buildx build --platform=linux/amd64 --no-cache=true -f Dockerfile -t placeholder-custom-db .

docker-sfomuseum:
	docker buildx build --platform=linux/amd64 --no-cache=true -f Dockerfile.sfomuseum -t placeholder-custom-db-sfomuseum .
